[project]
name = "video2text"
version = "0.1.0"
description = "Video Transcriber using faster-whisper"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "faster-whisper>=1.1.1",
    "ffmpeg-python>=0.2.0",
    "tqdm>=4.67.1",
]
